// packages/react/src/components/select/Select.tsx
import { Select as ArkSelect, useSelect, type CollectionItem } from "@ark-ui/react/select";
import { Portal } from "@ark-ui/react/portal";
import type { SelectProps as CoreSelectProps } from "@temporal-ui/core/select";
import { cx } from "@temporal-ui/core/utils/cx";
import { Field } from "../field";
import { SelectContent, type SelectItem } from "./SelectContent";
import { testId } from "@temporal-ui/core/utils/string";
import { ChevronsUpDown, X } from "lucide-react";

export interface SelectProps<D extends CollectionItem = never>
	extends CoreSelectProps<React.ReactNode>, ArkSelect.RootProps<SelectItem<D>> {}

export function Select<D extends CollectionItem>(props: SelectProps<D>) {
	const {
		label,
		hint,
		error,
		required,
		readOnly,
		disabled,
		classes,
		testId: testIdProp,
		icon,
		placeholder,
		portal,
		className,
		maxDropdownHeight,
		deselectable,
		...rootProps
	} = props;

	const select = useSelect({
		...rootProps,
		disabled,
		invalid: !!error,
		required,
		readOnly,
	});

	const tid = testId(testIdProp);

	return (
		<Field
			label={label}
			hint={hint}
			classes={classes}
			required={required}
			readOnly={readOnly}
			error={error}
			disabled={disabled}
			testId={tid("-field")}
		>
			<ArkSelect.RootProvider
				value={select}
				className={classes?.selectRoot}
				data-testid={tid("--root")}
			>
				<ArkSelect.Control
					aria-invalid={!!error}
					className={cx(classes?.control, className)}
					data-testid={tid("--control")}
				>
					<ArkSelect.Trigger className={classes?.trigger} data-testid={tid("--trigger")}>
						{select.selectedItems[0]?.icon || icon}
						<ArkSelect.ValueText
							className={classes?.valueText}
							placeholder={placeholder}
							data-testid={tid("--value-text")}
						/>
						{(!deselectable || !select.hasSelectedItems) && <ChevronsUpDown />}
					</ArkSelect.Trigger>
					{deselectable && select.hasSelectedItems && (
						<ArkSelect.ClearTrigger data-testid={tid("--clear-trigger")}>
							<X />
						</ArkSelect.ClearTrigger>
					)}
				</ArkSelect.Control>
				{portal && (
					<Portal>
						<SelectContent tid={tid} maxHeight={maxDropdownHeight} classes={classes} />
					</Portal>
				)}
				{!portal && <SelectContent tid={tid} maxHeight={maxDropdownHeight} classes={classes} />}
				<ArkSelect.HiddenSelect data-testid={tid("--input")} />
			</ArkSelect.RootProvider>
		</Field>
	);
}

// packages/solid/src/components/select/Select.tsx
import { Select as ArkSelect, useSelect } from "@ark-ui/solid/select";
import type { SelectProps as CoreSelectProps } from "@temporal-ui/core/select";
import { cx } from "@temporal-ui/core/utils/cx";
import { testId } from "@temporal-ui/core/utils/string";
import { ChevronsUpDown, X } from "lucide-solid";
import { mergeProps, Show, splitProps, type JSX } from "solid-js";
import { Portal } from "solid-js/web";
import { Field, fieldAttributes } from "../field";
import { SelectContent, type SelectItem } from "./SelectContent";

export interface SelectProps<D = unknown> extends CoreSelectProps<JSX.Element>, ArkSelect.RootProps<SelectItem<D>> {}

export function Select<D = unknown>(_props: SelectProps<D>) {
	const [fieldProps, controlProps, rootProps] = splitProps(_props, fieldAttributes, [
		"portal",
		"icon",
		"maxDropdownHeight",
		"className",
		"class",
		"deselectable",
		"placeholder",
	]);

	const useSelectProps = mergeProps(rootProps, {
		disabled: fieldProps.disabled,
		invalid: !!fieldProps.error,
		required: fieldProps.required,
		readOnly: fieldProps.readOnly,
	});

	const select = useSelect(useSelectProps);

	const tid = testId(fieldProps.testId);

	return (
		<Field {...fieldProps} testId={tid("-field")}>
			<ArkSelect.RootProvider value={select} class={fieldProps.classes?.selectRoot} data-testid={tid("--root")}>
				<ArkSelect.Control
					aria-invalid={!!fieldProps.error}
					class={cx(fieldProps.classes?.control, controlProps.class)}
					data-testid={tid("--control")}
				>
					<ArkSelect.Trigger class={fieldProps.classes?.trigger} data-testid={tid("--trigger")}>
						{select().selectedItems[0]?.icon || controlProps.icon}
						<ArkSelect.ValueText
							class={fieldProps.classes?.valueText}
							placeholder={controlProps.placeholder}
							data-testid={tid("--value-text")}
						/>
						<Show when={!controlProps.deselectable || !select().hasSelectedItems}>
							<ChevronsUpDown />
						</Show>
					</ArkSelect.Trigger>
					<Show when={controlProps.deselectable && select().hasSelectedItems}>
						<ArkSelect.ClearTrigger data-testid={tid("--clear-trigger")}>
							<X />
						</ArkSelect.ClearTrigger>
					</Show>
				</ArkSelect.Control>
				<Show when={controlProps.portal}>
					<Portal>
						<SelectContent tid={tid} maxHeight={controlProps.maxDropdownHeight} classes={fieldProps.classes} />
					</Portal>
				</Show>
				<Show when={!controlProps.portal}>
					<SelectContent tid={tid} maxHeight={controlProps.maxDropdownHeight} classes={fieldProps.classes} />
				</Show>
				<ArkSelect.HiddenSelect data-testid={tid("--input")} />
			</ArkSelect.RootProvider>
		</Field>
	);
}
