// packages/react/src/components/select/use-align-item-with-trigger.ts
import type { useSelectContext } from "@ark-ui/react/select";
import {
	ALIGN_ITEM_WITH_TRIGGER_MAX_RETRIES,
	alignItemWithTriggerFallbackPositioning,
	areAlignItemWithTriggerStylesEqual,
	computeAlignItemWithTrigger,
	querySelectedItemEl,
	type AlignItemWithTriggerStyles,
} from "@temporal-ui/core/select";
import { useLayoutEffect, useRef, useState } from "react";
import type { SelectContentProps } from "./SelectContent";

function runAfterLayout(callback: () => void) {
	requestAnimationFrame(() => {
		requestAnimationFrame(callback);
	});
}

export function useAlignItemWithTrigger(
	context: ReturnType<typeof useSelectContext>,
	props: Pick<
		SelectContentProps,
		"alignItemWithTrigger" | "alignItemWithTriggerMinHeight" | "openedWithTouch" | "selectIds"
	>,
) {
	const [alignedStyles, setAlignedStyles] = useState<AlignItemWithTriggerStyles | undefined>();
	const [alignEpoch, setAlignEpoch] = useState(0);
	const [readyEpoch, setReadyEpoch] = useState(0);
	const sessionRef = useRef(0);
	const propsRef = useRef(props);
	propsRef.current = props;

	const repositionRef = useRef(context.reposition);
	repositionRef.current = context.reposition;

	useLayoutEffect(() => {
		if (!context.open) {
			return;
		}

		const { alignItemWithTrigger, alignItemWithTriggerMinHeight, openedWithTouch, selectIds } =
			propsRef.current;

		if (!alignItemWithTrigger || openedWithTouch || context.multiple || !selectIds) {
			return;
		}

		sessionRef.current += 1;
		const session = sessionRef.current;
		setAlignEpoch(session);
		setAlignedStyles(undefined);

		let cancelled = false;
		let retries = 0;

		const fallbackToStandardPlacement = () => {
			setAlignedStyles(undefined);
			setReadyEpoch(session);
			repositionRef.current(alignItemWithTriggerFallbackPositioning);
		};

		const alignOnce = () => {
			if (cancelled || sessionRef.current !== session) {
				return;
			}

			const controlEl = document.getElementById(selectIds.control);
			const triggerEl = document.getElementById(selectIds.trigger);
			const valueTextEl = document.getElementById(selectIds.valueText);
			const positionerEl = document.getElementById(selectIds.positioner);
			const contentEl = document.getElementById(selectIds.content);

			if (!controlEl || !triggerEl || !valueTextEl || !positionerEl || !contentEl) {
				if (++retries >= ALIGN_ITEM_WITH_TRIGGER_MAX_RETRIES) {
					fallbackToStandardPlacement();
					return;
				}
				runAfterLayout(alignOnce);
				return;
			}

			const selectedItemEl = querySelectedItemEl(contentEl);
			if (!selectedItemEl) {
				fallbackToStandardPlacement();
				return;
			}

			const result = computeAlignItemWithTrigger({
				controlEl,
				triggerEl,
				valueTextEl,
				contentEl,
				positionerEl,
				selectedItemEl,
				minHeight: alignItemWithTriggerMinHeight,
			});

			if (cancelled || sessionRef.current !== session) {
				return;
			}

			if (result.status === "fallback") {
				fallbackToStandardPlacement();
				return;
			}

			setAlignedStyles((current) =>
				areAlignItemWithTriggerStylesEqual(current, result.styles) ? current : result.styles,
			);
			setReadyEpoch(session);
		};

		queueMicrotask(() => {
			runAfterLayout(alignOnce);
		});

		return () => {
			cancelled = true;
		};
	}, [context.open]);

	// Scroll after the aligned styles are committed: the target offset is computed
	// for the final popup height and would be clamped by the pending max-height.
	useLayoutEffect(() => {
		if (!alignedStyles || !context.open || !props.selectIds) {
			return;
		}
		const contentEl = document.getElementById(props.selectIds.content);
		if (contentEl) {
			contentEl.scrollTop = alignedStyles.scrollTop;
		}
	}, [alignedStyles, context.open, props.selectIds]);

	const shouldAlign = !!(
		props.alignItemWithTrigger &&
		!props.openedWithTouch &&
		!context.multiple &&
		props.selectIds
	);

	const isAlignPending = shouldAlign && context.open && readyEpoch !== alignEpoch;
	const showAligned = !!alignedStyles && context.open && !isAlignPending;

	return { alignedStyles, isAlignPending, showAligned, shouldAlign };
}

// packages/solid/src/components/select/use-align-item-with-trigger.ts
import type { useSelectContext } from "@ark-ui/solid/select";
import {
	ALIGN_ITEM_WITH_TRIGGER_MAX_RETRIES,
	alignItemWithTriggerFallbackPositioning,
	areAlignItemWithTriggerStylesEqual,
	computeAlignItemWithTrigger,
	querySelectedItemEl,
	type AlignItemWithTriggerStyles,
} from "@temporal-ui/core/select";
import { createEffect, createMemo, createSignal, onCleanup, untrack } from "solid-js";
import type { SelectContentProps } from "./SelectContent";

function runAfterLayout(callback: () => void) {
	requestAnimationFrame(() => {
		requestAnimationFrame(callback);
	});
}

/** Solid's `style` binding drops camelCase keys; convert to kebab-case. */
function toKebabStyles(styles: Record<string, string>): Record<string, string> {
	return Object.fromEntries(
		Object.entries(styles).map(([key, value]) => [
			key.replace(/[A-Z]/g, (char) => `-${char.toLowerCase()}`),
			value,
		]),
	);
}

function toSolidStyles(styles: AlignItemWithTriggerStyles): AlignItemWithTriggerStyles {
	return {
		positioner: toKebabStyles(styles.positioner),
		popup: toKebabStyles(styles.popup),
		content: toKebabStyles(styles.content),
		scrollTop: styles.scrollTop,
	};
}

export function useAlignItemWithTrigger(
	context: ReturnType<typeof useSelectContext>,
	props: () => Pick<
		SelectContentProps,
		"alignItemWithTrigger" | "alignItemWithTriggerMinHeight" | "openedWithTouch" | "selectIds"
	>,
) {
	const [alignedStyles, setAlignedStyles] = createSignal<AlignItemWithTriggerStyles | undefined>();
	const [alignEpoch, setAlignEpoch] = createSignal(0);
	const [readyEpoch, setReadyEpoch] = createSignal(0);
	const isOpen = createMemo(() => context().open);
	let sessionCounter = 0;

	const shouldAlign = createMemo(() => {
		const currentProps = props();
		return (
			!!currentProps.alignItemWithTrigger &&
			!currentProps.openedWithTouch &&
			!untrack(() => context().multiple) &&
			!!currentProps.selectIds
		);
	});

	const isAlignPending = createMemo(
		() => shouldAlign() && isOpen() && readyEpoch() !== alignEpoch(),
	);

	const showAligned = createMemo(() => !!alignedStyles() && isOpen() && !isAlignPending());

	createEffect(() => {
		if (!isOpen()) {
			return;
		}

		const currentProps = untrack(props);
		if (
			!currentProps.alignItemWithTrigger ||
			currentProps.openedWithTouch ||
			untrack(() => context().multiple) ||
			!currentProps.selectIds
		) {
			return;
		}

		const session = ++sessionCounter;
		setAlignEpoch(session);
		setAlignedStyles(undefined);

		let cancelled = false;
		let retries = 0;

		const fallbackToStandardPlacement = () => {
			setAlignedStyles(undefined);
			setReadyEpoch(session);
			untrack(() => context()).reposition(alignItemWithTriggerFallbackPositioning);
		};

		const alignOnce = () => {
			if (cancelled || sessionCounter !== session) {
				return;
			}

			const ids = currentProps.selectIds;
			if (!ids) {
				fallbackToStandardPlacement();
				return;
			}

			const controlEl = document.getElementById(ids.control);
			const triggerEl = document.getElementById(ids.trigger);
			const valueTextEl = document.getElementById(ids.valueText);
			const positionerEl = document.getElementById(ids.positioner);
			const contentEl = document.getElementById(ids.content);

			if (!controlEl || !triggerEl || !valueTextEl || !positionerEl || !contentEl) {
				if (++retries >= ALIGN_ITEM_WITH_TRIGGER_MAX_RETRIES) {
					fallbackToStandardPlacement();
					return;
				}
				runAfterLayout(alignOnce);
				return;
			}

			const selectedItemEl = querySelectedItemEl(contentEl);
			if (!selectedItemEl) {
				fallbackToStandardPlacement();
				return;
			}

			const result = computeAlignItemWithTrigger({
				controlEl,
				triggerEl,
				valueTextEl,
				contentEl,
				positionerEl,
				selectedItemEl,
				minHeight: currentProps.alignItemWithTriggerMinHeight,
			});

			if (cancelled || sessionCounter !== session) {
				return;
			}

			if (result.status === "fallback") {
				fallbackToStandardPlacement();
				return;
			}

			const styles = toSolidStyles(result.styles);
			setAlignedStyles((current) =>
				areAlignItemWithTriggerStylesEqual(current, styles) ? current : styles,
			);
			setReadyEpoch(session);
		};

		queueMicrotask(() => {
			runAfterLayout(alignOnce);
		});

		onCleanup(() => {
			cancelled = true;
		});
	});

	// Scroll after the aligned styles are committed: the target offset is computed
	// for the final popup height and would be clamped by the pending max-height.
	createEffect(() => {
		const styles = alignedStyles();
		const ids = props().selectIds;
		if (!styles || !isOpen() || !ids) {
			return;
		}
		const contentEl = document.getElementById(ids.content);
		if (contentEl) {
			contentEl.scrollTop = styles.scrollTop;
		}
	});

	return { alignedStyles, isAlignPending, showAligned, shouldAlign };
}
