// packages/solid/src/components/menu/MenuRadioItem.tsx
import { Menu as ArkMenu } from "@ark-ui/solid/menu";
import type { MenuRadioItemProps as CoreMenuRadioItemProps } from "@temporal-ui/core/menu";
import { testId } from "@temporal-ui/core/utils/string";
import { splitProps } from "solid-js";
import type { ComponentProps } from "solid-js";

export interface MenuRadioItemProps extends CoreMenuRadioItemProps, ComponentProps<typeof ArkMenu.RadioItem> {}

export function MenuRadioItem(props: MenuRadioItemProps) {
	const [localProps, radioItemProps] = splitProps(props, ["className", "testId"]);

	const tid = testId(localProps.testId);

	return (
		<ArkMenu.RadioItem {...radioItemProps} class={localProps.className} data-testid={tid("--radio-item")}>
			<ArkMenu.ItemIndicator data-testid={tid("--indicator")}>
				<div data-part="item-radio-indicator" />
			</ArkMenu.ItemIndicator>
			<ArkMenu.ItemText data-testid={tid("--text")}>{props.children}</ArkMenu.ItemText>
		</ArkMenu.RadioItem>
	);
}

// packages/react/src/components/menu/MenuRadioItem.tsx
import { Menu as ArkMenu } from "@ark-ui/react/menu";
import type { MenuRadioItemProps as CoreMenuRadioItemProps } from "@temporal-ui/core/menu";
import type React from "react";
import { testId as testIdFn } from "@temporal-ui/core/utils/string";

export interface MenuRadioItemProps
	extends CoreMenuRadioItemProps, React.ComponentProps<typeof ArkMenu.RadioItem> {}

export function MenuRadioItem(props: MenuRadioItemProps) {
	const { testId, children, ...rest } = props;
	const tid = testIdFn(testId);

	return (
		<ArkMenu.RadioItem {...rest} data-testid={tid("--radio-item")}>
			<ArkMenu.ItemIndicator data-testid={tid("--indicator")}>
				<div data-part="item-radio-indicator" />
			</ArkMenu.ItemIndicator>
			<ArkMenu.ItemText data-testid={tid("--text")}>{children}</ArkMenu.ItemText>
		</ArkMenu.RadioItem>
	);
}
