// packages/solid/src/components/menu/MenuSub.tsx
import { Menu as ArkMenu } from "@ark-ui/solid/menu";
import type { MenuSubProps as CoreMenuSubProps } from "@temporal-ui/core/menu";
import { testId } from "@temporal-ui/core/utils/string";
import { splitProps, type ComponentProps, type JSX, type ParentProps } from "solid-js";
import { Box } from "../box";

const defaultSubPosition = {
	placement: "right-start" as const,
	gutter: -2,
};

export interface MenuSubProps
	extends
		CoreMenuSubProps<JSX.Element>,
		Omit<ComponentProps<typeof ArkMenu.Root>, "positioning" | "children" | "onSelect">,
		ParentProps {}

export function MenuSub(_props: MenuSubProps) {
	const [localProps, rootProps] = splitProps(_props, [
		"className",
		"testId",
		"position",
		"children",
		"onSelect",
	]);

	const tid = testId(localProps.testId);

	return (
		<ArkMenu.Root
			{...rootProps}
			onSelect={(details) => localProps.onSelect?.(details.value)}
			positioning={{
				...defaultSubPosition,
				...localProps.position,
			}}
			data-testid={tid("--sub-root")}
		>
			{localProps.className !== undefined ? (
				<Box class={localProps.className} testId={tid("--sub-inner")}>
					{localProps.children}
				</Box>
			) : (
				localProps.children
			)}
		</ArkMenu.Root>
	);
}

// packages/react/src/components/menu/MenuSub.tsx
import type { MenuSubProps as CoreMenuSubProps } from "@temporal-ui/core/menu";
import { Menu as ArkMenu } from "@ark-ui/react/menu";
import type React from "react";
import { testId as testIdFn } from "@temporal-ui/core/utils/string";
import { Box } from "../box";

const defaultSubPosition = {
	placement: "right-start" as const,
	gutter: -2,
};

export interface MenuSubProps
	extends
		CoreMenuSubProps<React.ReactNode>,
		Omit<React.ComponentProps<typeof ArkMenu.Root>, "positioning" | "children" | "onSelect"> {
	children: React.ReactNode;
}

export function MenuSub(props: MenuSubProps) {
	const { children, className, position, testId, onSelect, ...rootProps } = props;
	const tid = testIdFn(testId);

	return (
		<ArkMenu.Root
			{...rootProps}
			onSelect={(details) => onSelect?.(details.value)}
			positioning={{
				...defaultSubPosition,
				...position,
			}}
			data-testid={tid("--sub-root")}
		>
			{className !== undefined ? (
				<Box className={className} testId={tid("--sub-inner")}>
					{children}
				</Box>
			) : (
				children
			)}
		</ArkMenu.Root>
	);
}
