// packages/react/src/components/menu/MenuItemSeparator.tsx
import type { MenuItemSeparatorProps as CoreMenuItemSeparatorProps } from "@temporal-ui/core/menu";
import { Menu as ArkMenu } from "@ark-ui/react/menu";
import type React from "react";

export interface MenuItemSeparatorProps
	extends CoreMenuItemSeparatorProps, React.ComponentProps<typeof ArkMenu.Separator> {}

export function MenuItemSeparator(props: MenuItemSeparatorProps) {
	const { testId, ...rest } = props;

	return <ArkMenu.Separator {...rest} data-testid={testId} />;
}

// packages/solid/src/components/menu/MenuItemSeparator.tsx
import { Menu as ArkMenu } from "@ark-ui/solid/menu";
import type { MenuItemSeparatorProps as CoreMenuItemSeparatorProps } from "@temporal-ui/core/menu";
import type { ComponentProps } from "solid-js";
import { splitProps } from "solid-js";

export interface MenuItemSeparatorProps extends CoreMenuItemSeparatorProps, ComponentProps<typeof ArkMenu.Separator> {}

export function MenuItemSeparator(props: MenuItemSeparatorProps) {
	const [localProps, separatorProps] = splitProps(props, ["className", "testId"]);
	return <ArkMenu.Separator {...separatorProps} class={localProps.className} data-testid={localProps.testId} />;
}
