// packages/react/src/components/menu/MenuSubTrigger.tsx
import type { MenuSubTriggerProps as CoreMenuSubTriggerProps } from "@temporal-ui/core/menu";
import { Menu as ArkMenu } from "@ark-ui/react/menu";
import type React from "react";

export interface MenuSubTriggerProps
	extends CoreMenuSubTriggerProps, React.ComponentProps<typeof ArkMenu.TriggerItem> {}

export function MenuSubTrigger(props: MenuSubTriggerProps) {
	const { testId, className, ...rest } = props;

	return (
		<ArkMenu.TriggerItem {...rest} className={className} data-testid={testId}>
			{props.children}
		</ArkMenu.TriggerItem>
	);
}

// packages/solid/src/components/menu/MenuSubTrigger.tsx
import { Menu as ArkMenu } from "@ark-ui/solid/menu";
import type { MenuSubTriggerProps as CoreMenuSubTriggerProps } from "@temporal-ui/core/menu";
import { splitProps, type ComponentProps } from "solid-js";

export interface MenuSubTriggerProps
	extends CoreMenuSubTriggerProps, ComponentProps<typeof ArkMenu.TriggerItem> {}

export function MenuSubTrigger(props: MenuSubTriggerProps) {
	const [localProps, triggerProps] = splitProps(props, ["className", "testId"]);

	return (
		<ArkMenu.TriggerItem
			{...triggerProps}
			class={localProps.className}
			data-testid={localProps.testId}
		/>
	);
}
