// packages/react/src/components/menu/MenuSubContent.tsx
import type { MenuSubContentProps as CoreMenuSubContentProps } from "@temporal-ui/core/menu";
import { Menu as ArkMenu } from "@ark-ui/react/menu";
import type React from "react";
import { Portal } from "@ark-ui/react/portal";
import { testId as testIdFn } from "@temporal-ui/core/utils/string";

export interface MenuSubContentProps extends CoreMenuSubContentProps, React.ComponentProps<typeof ArkMenu.Content> {}

export function MenuSubContent(props: MenuSubContentProps) {
	const { testId, className, children, ...rest } = props;
	const tid = testIdFn(testId);

	return (
		<Portal>
			<ArkMenu.Positioner data-testid={tid("--sub-positioner")}>
				<ArkMenu.Content {...rest} className={className} data-testid={tid("--sub-content")}>
					{children}
				</ArkMenu.Content>
			</ArkMenu.Positioner>
		</Portal>
	);
}

// packages/solid/src/components/menu/MenuSubContent.tsx
import { Menu as ArkMenu } from "@ark-ui/solid/menu";
import type { MenuSubContentProps as CoreMenuSubContentProps } from "@temporal-ui/core/menu";
import { testId } from "@temporal-ui/core/utils/string";
import { Portal } from "solid-js/web";
import { splitProps, type ComponentProps } from "solid-js";

export interface MenuSubContentProps
	extends CoreMenuSubContentProps, ComponentProps<typeof ArkMenu.Content> {}

export function MenuSubContent(props: MenuSubContentProps) {
	const [localProps, contentProps] = splitProps(props, ["className", "testId"]);

	const tid = testId(localProps.testId);

	return (
		<Portal>
			<ArkMenu.Positioner data-testid={tid("--sub-positioner")}>
				<ArkMenu.Content {...contentProps} class={localProps.className} data-testid={tid("--sub-content")} />
			</ArkMenu.Positioner>
		</Portal>
	);
}
