// packages/react/src/components/menu/Menu.tsx
import type { MenuProps as CoreMenuProps } from "@temporal-ui/core/menu";
import { Menu as ArkMenu } from "@ark-ui/react/menu";
import type React from "react";
import { Portal } from "@ark-ui/react/portal";
import { testId as testIdFn } from "@temporal-ui/core/utils/string";

export interface MenuProps
	extends
		CoreMenuProps<React.ReactNode>,
		Omit<React.ComponentProps<typeof ArkMenu.Root>, "onSelect"> {
	trigger: React.ReactNode;
}

export function Menu(props: MenuProps) {
	const { trigger, children, className, onSelect, testId, position, ...rootProps } = props;

	const tid = testIdFn(testId);

	return (
		<ArkMenu.Root
			{...rootProps}
			onSelect={(details) => onSelect?.(details.value)}
			data-testid={tid("--root")}
			positioning={position}
		>
			<ArkMenu.Trigger data-testid={tid("--trigger")} asChild>
				{trigger}
			</ArkMenu.Trigger>
			<Portal>
				<ArkMenu.Positioner data-testid={tid("--positioner")}>
					<ArkMenu.Content className={className} data-testid={tid("--content")}>
						{children}
					</ArkMenu.Content>
				</ArkMenu.Positioner>
			</Portal>
		</ArkMenu.Root>
	);
}

// packages/solid/src/components/menu/Menu.tsx
import { Menu as ArkMenu } from "@ark-ui/solid/menu";
import type { MenuProps as CoreMenuProps } from "@temporal-ui/core/menu";
import { testId } from "@temporal-ui/core/utils/string";
import { splitProps, type ComponentProps, type JSX, type ParentProps } from "solid-js";
import { Portal } from "solid-js/web";

export interface MenuProps
	extends CoreMenuProps<JSX.Element>, Omit<ComponentProps<typeof ArkMenu.Root>, "onSelect" | "positioning"> {
	trigger: (props: ParentProps) => JSX.Element;
}

export function Menu(_props: MenuProps) {
	const [localProps, rootProps] = splitProps(_props, [
		"trigger",
		"testId",
		"position",
		"onSelect",
		"className",
		"children",
	]);

	const tid = testId(localProps.testId);

	return (
		<ArkMenu.Root
			{...rootProps}
			onSelect={(details) => localProps.onSelect?.(details.value)}
			positioning={localProps.position}
			data-testid={tid("--root")}
		>
			<ArkMenu.Trigger asChild={(props) => localProps.trigger(props())} data-testid={tid("--trigger")} />
			<Portal>
				<ArkMenu.Positioner data-testid={tid("--positioner")}>
					<ArkMenu.Content class={localProps.className} data-testid={localProps.testId}>
						{localProps.children}
					</ArkMenu.Content>
				</ArkMenu.Positioner>
			</Portal>
		</ArkMenu.Root>
	);
}
