// packages/react/src/components/date-input/YearView.tsx
/** biome-ignore-all lint/suspicious/noArrayIndexKey: Default behavior from Ark UI examples */
import { DatePicker } from "@ark-ui/react/date-picker";

export function YearView() {
	return (
		<DatePicker.View view="year" data-scope={"date-input"} data-view="year">
			<DatePicker.Context>
				{(datePicker) => (
					<>
						<DatePicker.Table data-scope={"date-input"}>
							<DatePicker.TableBody data-scope={"date-input"}>
								{datePicker.getYearsGrid({ columns: 4 }).map((years, id) => (
									<DatePicker.TableRow data-scope={"date-input"} key={id}>
										{years.map((year, id) => (
											<DatePicker.TableCell data-scope={"date-input"} key={id} value={year.value}>
												<DatePicker.TableCellTrigger data-scope={"date-input"}>
													{year.label}
												</DatePicker.TableCellTrigger>
											</DatePicker.TableCell>
										))}
									</DatePicker.TableRow>
								))}
							</DatePicker.TableBody>
						</DatePicker.Table>
					</>
				)}
			</DatePicker.Context>
		</DatePicker.View>
	);
}

// packages/solid/src/components/date-input/YearView.tsx
import { DatePicker } from "@ark-ui/solid/date-picker";
import { Index } from "solid-js";

export function YearView() {
	return (
		<DatePicker.View view="year" data-scope={"date-input"} data-view="year">
			<DatePicker.Context>
				{(datePicker) => (
					<>
						<DatePicker.Table data-scope={"date-input"}>
							<DatePicker.TableBody data-scope={"date-input"}>
								<Index each={datePicker().getYearsGrid({ columns: 4 })}>
									{(years) => (
										<DatePicker.TableRow data-scope={"date-input"}>
											<Index each={years()}>
												{(year) => (
													<DatePicker.TableCell data-scope={"date-input"} value={year().value}>
														<DatePicker.TableCellTrigger data-scope={"date-input"}>
															{year().label}
														</DatePicker.TableCellTrigger>
													</DatePicker.TableCell>
												)}
											</Index>
										</DatePicker.TableRow>
									)}
								</Index>
							</DatePicker.TableBody>
						</DatePicker.Table>
					</>
				)}
			</DatePicker.Context>
		</DatePicker.View>
	);
}
