// packages/react/src/components/tooltip/TooltipProvider.tsx
import { Tooltip as ArkTooltip } from "@ark-ui/react/tooltip";
import type React from "react";
import { createContext, useContext } from "react";

export type TooltipConfig = React.ComponentProps<typeof ArkTooltip.Root>;

export interface TooltipProviderProps extends TooltipConfig {
	children?: React.ReactNode;
}

const TooltipConfigContext = createContext<TooltipConfig>({});

export function TooltipProvider(props: TooltipProviderProps) {
	const { children, ...arkRoot } = props;
	const value = { ...useTooltipConfig(), ...arkRoot };

	return <TooltipConfigContext.Provider value={value}>{children}</TooltipConfigContext.Provider>;
}

export function useTooltipConfig(): TooltipConfig {
	return useContext(TooltipConfigContext);
}

// packages/solid/src/components/tooltip/TooltipProvider.tsx
import { Tooltip as ArkTooltip } from "@ark-ui/solid/tooltip";
import {
	createContext,
	mergeProps,
	splitProps,
	useContext,
	type ComponentProps,
	type JSX,
} from "solid-js";

export type TooltipConfig = ComponentProps<typeof ArkTooltip.Root>;

export interface TooltipProviderProps extends TooltipConfig {
	children?: JSX.Element;
}

const TooltipConfigContext = createContext({} as TooltipConfig);

export function TooltipProvider(props: TooltipProviderProps) {
	const [local, arkRoot] = splitProps(props, ["children"]);
	const value = mergeProps(useTooltipConfig(), arkRoot);

	return (
		<TooltipConfigContext.Provider value={value}>{local.children}</TooltipConfigContext.Provider>
	);
}

export function useTooltipConfig() {
	return useContext(TooltipConfigContext);
}
