// packages/react/src/components/tooltip/Tooltip.tsx
import { Tooltip as ArkTooltip } from "@ark-ui/react/tooltip";
import type { BaseComponent } from "@temporal-ui/core/base";
import {
	DISABLED_TOOLTIP_TRIGGER_TAB_INDEX,
	isDisabledControlProps,
	shouldWrapDisabledTooltipTrigger,
	type TooltipBaseProps,
} from "@temporal-ui/core/tooltip";
import { testId as testIdFn } from "@temporal-ui/core/utils/string";
import type React from "react";
import { isValidElement } from "react";
import { TooltipContent } from "./TooltipContent";
import { useTooltipConfig } from "./TooltipProvider";

export interface TooltipProps
	extends
		Omit<React.ComponentProps<typeof ArkTooltip.Root>, "onOpenChange">,
		TooltipBaseProps<React.ReactNode>,
		Pick<BaseComponent<React.ReactNode>, "testId" | "className"> {
	trigger?: React.ReactNode;
	onOpenChange?: (open: boolean) => void;
}

function isTriggerDisabled(trigger: React.ReactNode): boolean {
	if (!isValidElement(trigger)) {
		return false;
	}
	return isDisabledControlProps(trigger.props as Record<string, unknown>);
}

export function Tooltip(props: TooltipProps) {
	const { trigger, testId, className, children, onOpenChange, disabledTrigger, ...instanceRoot } =
		props;
	const arkRoot = { ...useTooltipConfig(), ...instanceRoot };
	const tid = testIdFn(testId);
	const wrapDisabledTrigger = shouldWrapDisabledTooltipTrigger(
		disabledTrigger,
		trigger ? isTriggerDisabled(trigger) : false,
	);

	return (
		<ArkTooltip.Root
			{...arkRoot}
			onOpenChange={(details) => onOpenChange?.(details.open)}
			data-testid={tid("--root")}
		>
			{trigger && (
				<ArkTooltip.Trigger asChild data-testid={tid("--trigger")}>
					{wrapDisabledTrigger ? (
						<span
							data-scope="tooltip"
							data-part="trigger-wrapper"
							tabIndex={DISABLED_TOOLTIP_TRIGGER_TAB_INDEX}
						>
							{trigger}
						</span>
					) : (
						trigger
					)}
				</ArkTooltip.Trigger>
			)}
			<TooltipContent testId={testId} className={className}>
				{children}
			</TooltipContent>
		</ArkTooltip.Root>
	);
}

// packages/solid/src/components/tooltip/Tooltip.tsx
import { Tooltip as ArkTooltip } from "@ark-ui/solid/tooltip";
import type { BaseComponent } from "@temporal-ui/core/base";
import {
	DISABLED_TOOLTIP_TRIGGER_TAB_INDEX,
	shouldWrapDisabledTooltipTrigger,
	type TooltipBaseProps,
} from "@temporal-ui/core/tooltip";
import { testId } from "@temporal-ui/core/utils/string";
import { mergeProps, Show, splitProps, type ComponentProps, type JSX } from "solid-js";
import { TooltipContent as TemporalTooltipContent } from "./TooltipContent";
import { useTooltipConfig } from "./TooltipProvider";

export interface TooltipProps
	extends
		Omit<ComponentProps<typeof ArkTooltip.Root>, "onOpenChange">,
		TooltipBaseProps<JSX.Element>,
		Pick<BaseComponent<JSX.Element>, "testId" | "className"> {
	trigger?: (props: Record<string, unknown>) => JSX.Element;
	onOpenChange?: (open: boolean) => void;
}

export function Tooltip(props: TooltipProps) {
	const [local, rest] = splitProps(props, [
		"trigger",
		"testId",
		"className",
		"children",
		"onOpenChange",
		"disabledTrigger",
	]);
	const arkRoot = mergeProps(useTooltipConfig(), rest);
	const tid = testId(local.testId);
	const wrapDisabledTrigger = () => shouldWrapDisabledTooltipTrigger(local.disabledTrigger, false);

	return (
		<ArkTooltip.Root
			{...arkRoot}
			onOpenChange={(details) => local.onOpenChange?.(details.open)}
			data-testid={tid("--root")}
		>
			<Show when={local.trigger}>
				<ArkTooltip.Trigger
					asChild={(triggerProps) => {
						if (wrapDisabledTrigger()) {
							return (
								<span
									{...triggerProps()}
									data-scope="tooltip"
									data-part="trigger-wrapper"
									tabIndex={DISABLED_TOOLTIP_TRIGGER_TAB_INDEX}
								>
									{local.trigger?.({})}
								</span>
							);
						}
						return local.trigger?.({ ...triggerProps() });
					}}
					data-testid={tid("--trigger")}
				/>
			</Show>
			<TemporalTooltipContent
				testId={local.testId}
				className={local.className}
				children={local.children}
			/>
		</ArkTooltip.Root>
	);
}
