// packages/react/src/components/slider/Slider.tsx
import type { SliderProps as CoreSliderProps } from "@temporal-ui/core/slider";
import { Slider as ArkSlider } from "@ark-ui/react/slider";
import type React from "react";
import { Field } from "../field";
import { forwardRef } from "react";
export interface SliderProps
	extends
		CoreSliderProps<React.ReactNode>,
		Omit<React.InputHTMLAttributes<HTMLInputElement>, "max" | "min" | "step"> {}

export const Slider = forwardRef<HTMLInputElement, SliderProps & ArkSlider.RootProps>(
	(props, ref) => {
		const {
			label,
			hint,
			error,
			required,
			readOnly,
			disabled,
			testId,
			showValue,
			marks,
			showMarkDashes,
			...rootProps
		} = props;
		return (
			<Field
				label={label}
				hint={hint}
				required={required}
				readOnly={readOnly}
				disabled={disabled}
				error={error}
				testId={props.testId ? `${props.testId}-field` : undefined}
			>
				<ArkSlider.Root
					{...rootProps}
					readOnly={readOnly}
					disabled={disabled}
					data-testid={testId ? `${testId}--root` : undefined}
				>
					<ArkSlider.Control data-with-value={showValue}>
						<ArkSlider.Track>
							<ArkSlider.Range />
						</ArkSlider.Track>
						<ArkSlider.Thumb index={0}>
							<ArkSlider.HiddenInput
								ref={ref}
								data-testid={testId ? `${testId}--input` : undefined}
							/>
							{showValue && <ArkSlider.ValueText />}
						</ArkSlider.Thumb>
					</ArkSlider.Control>
					{marks && (
						<ArkSlider.MarkerGroup data-with-dashes={showMarkDashes ? true : undefined}>
							{Object.entries(marks).map(([value, label]) => (
								<ArkSlider.Marker key={value} value={Number(value)}>
									{label}
								</ArkSlider.Marker>
							))}
						</ArkSlider.MarkerGroup>
					)}
				</ArkSlider.Root>
			</Field>
		);
	},
);

// packages/solid/src/components/slider/Slider.tsx
import type { SliderProps as CoreSliderProps } from "@temporal-ui/core/slider";
import { Slider as ArkSlider } from "@ark-ui/solid/slider";
import { Field } from "../field";
import { For, Show, splitProps, type JSX } from "solid-js";
export interface SliderProps extends CoreSliderProps<JSX.Element> {}

export function Slider(props: SliderProps & ArkSlider.RootProps) {
	const [fieldProps, controlProps, rootProps] = splitProps(
		props,
		["label", "hint", "error", "required", "readOnly", "disabled", "testId", "classes"],
		["showValue", "marks", "showMarkDashes"],
	);
	return (
		<Field {...fieldProps} testId={props.testId ? `${props.testId}-field` : undefined}>
			<ArkSlider.Root
				{...rootProps}
				readOnly={fieldProps.readOnly}
				disabled={fieldProps.disabled}
				data-testid={fieldProps.testId ? `${fieldProps.testId}--root` : undefined}
			>
				<ArkSlider.Control data-with-value={controlProps.showValue}>
					<ArkSlider.Track>
						<ArkSlider.Range />
					</ArkSlider.Track>
					<ArkSlider.Thumb index={0}>
						<ArkSlider.HiddenInput
							data-testid={fieldProps.testId ? `${fieldProps.testId}--input` : undefined}
						/>
						<Show when={controlProps.showValue}>
							<ArkSlider.ValueText />
						</Show>
					</ArkSlider.Thumb>
				</ArkSlider.Control>
				<Show when={controlProps.marks}>
					<ArkSlider.MarkerGroup data-with-dashes={controlProps.showMarkDashes ? true : undefined}>
						<For each={Object.entries(controlProps.marks || {})}>
							{([value, label]) => (
								<ArkSlider.Marker value={Number(value)}>{label}</ArkSlider.Marker>
							)}
						</For>
					</ArkSlider.MarkerGroup>
				</Show>
			</ArkSlider.Root>
		</Field>
	);
}
